name: FakeMain
# simulate QA step of a PR : in fact awaiting 10 seconds and success

# WHEN the action will run.
on:
  # Trigger ON PUSH or PULL REQUEST events for the main branch
  push:
    branches:
     - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: fake_QA_await_10sec
      run: |
        echo "(fake) QA in progress ..."
        sleep 10
        echo "... OK"
