name: Try_win
# this workflow is triggered from UI
on:
  workflow_dispatch:

jobs:
  build:
    # maybe https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on:  windows-2022
    # runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: check applications installed
        run: |
         echo "npm --version"
         npm --version
         echo "jq --version"
         jq --version

      - name: Check and Set Package Version
        run: node .github/publish_step1_check_version.js
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
      - name: show env
        id: show_env
        run: |
          echo "env.VERSION:${{ env.VERSION }}"